name: iOS App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build iosApp Scheme
        run: |
          cd client/swiftui-app/iosApp
          xcodebuild build-for-testing -scheme iosApp build -target Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO